project_id = "pfvsbsrlycnclpluiars"

[functions.auth-email-hook]
verify_jwt = false

[functions.invite-mentor]
verify_jwt = true

[functions.request-apk-upload]
verify_jwt = false

[functions.download-apk]
verify_jwt = false

[functions.preview-transactional-email]
verify_jwt = false
