/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as VerifyIdRouteImport } from './routes/verify-id'
import { Route as AppAdminReviewRouteImport } from './routes/app.admin-review'
import { Route as AppBlockedRouteImport } from './routes/app.blocked'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppMatchesRouteImport } from './routes/app.matches'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as ChatMatchIdRouteImport } from './routes/chat.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify-id',
  path: '/verify-id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminReviewRoute = AppAdminReviewRouteImport.update({
  id: '/admin-review',
  path: '/admin-review',
  getParentRoute: () => AppRoute,
} as any)
const AppBlockedRoute = AppBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const ChatMatchIdRoute = ChatMatchIdRouteImport.update({
  id: '/chat/$matchId',
  path: '/chat/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-id': typeof VerifyIdRoute
  '/app/admin-review': typeof AppAdminReviewRoute
  '/app/blocked': typeof AppBlockedRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-id': typeof VerifyIdRoute
  '/app/admin-review': typeof AppAdminReviewRoute
  '/app/blocked': typeof AppBlockedRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/verify-id': typeof VerifyIdRoute
  '/app/admin-review': typeof AppAdminReviewRoute
  '/app/blocked': typeof AppBlockedRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/verify-id'
    | '/app/admin-review'
    | '/app/blocked'
    | '/app/discover'
    | '/app/matches'
    | '/app/profile'
    | '/chat/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/verify-id'
    | '/app/admin-review'
    | '/app/blocked'
    | '/app/discover'
    | '/app/matches'
    | '/app/profile'
    | '/chat/$matchId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/verify-id'
    | '/app/admin-review'
    | '/app/blocked'
    | '/app/discover'
    | '/app/matches'
    | '/app/profile'
    | '/chat/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  VerifyIdRoute: typeof VerifyIdRoute
  ChatMatchIdRoute: typeof ChatMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-id': {
      id: '/verify-id'
      path: '/verify-id'
      fullPath: '/verify-id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin-review': {
      id: '/app/admin-review'
      path: '/admin-review'
      fullPath: '/app/admin-review'
      preLoaderRoute: typeof AppAdminReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/blocked': {
      id: '/app/blocked'
      path: '/blocked'
      fullPath: '/app/blocked'
      preLoaderRoute: typeof AppBlockedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches': {
      id: '/app/matches'
      path: '/matches'
      fullPath: '/app/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/chat/$matchId': {
      id: '/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/chat/$matchId'
      preLoaderRoute: typeof ChatMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminReviewRoute: typeof AppAdminReviewRoute
  AppBlockedRoute: typeof AppBlockedRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminReviewRoute: AppAdminReviewRoute,
  AppBlockedRoute: AppBlockedRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  VerifyIdRoute: VerifyIdRoute,
  ChatMatchIdRoute: ChatMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
