/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyIdRouteImport } from './routes/verify-id'
import { Route as VerifyChurchRouteImport } from './routes/verify-church'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as ChooseTypeRouteImport } from './routes/choose-type'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteMentorRouteImport } from './routes/invite.mentor'
import { Route as ChatMatchIdRouteImport } from './routes/chat.$matchId'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMatchesRouteImport } from './routes/app.matches'
import { Route as AppEditProfileRouteImport } from './routes/app.edit-profile'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppAdminReviewRouteImport } from './routes/app.admin-review'

const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify-id',
  path: '/verify-id',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyChurchRoute = VerifyChurchRouteImport.update({
  id: '/verify-church',
  path: '/verify-church',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseTypeRoute = ChooseTypeRouteImport.update({
  id: '/choose-type',
  path: '/choose-type',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteMentorRoute = InviteMentorRouteImport.update({
  id: '/invite/mentor',
  path: '/invite/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatMatchIdRoute = ChatMatchIdRouteImport.update({
  id: '/chat/$matchId',
  path: '/chat/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchesRoute = AppMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AppRoute,
} as any)
const AppEditProfileRoute = AppEditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminReviewRoute = AppAdminReviewRouteImport.update({
  id: '/admin-review',
  path: '/admin-review',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/choose-type': typeof ChooseTypeRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/verify-church': typeof VerifyChurchRoute
  '/verify-id': typeof VerifyIdRoute
  '/app/admin-review': typeof AppAdminReviewRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/edit-profile': typeof AppEditProfileRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
  '/invite/mentor': typeof InviteMentorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/choose-type': typeof ChooseTypeRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/verify-church': typeof VerifyChurchRoute
  '/verify-id': typeof VerifyIdRoute
  '/app/admin-review': typeof AppAdminReviewRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/edit-profile': typeof AppEditProfileRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
  '/invite/mentor': typeof InviteMentorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/choose-type': typeof ChooseTypeRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/verify-church': typeof VerifyChurchRoute
  '/verify-id': typeof VerifyIdRoute
  '/app/admin-review': typeof AppAdminReviewRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/edit-profile': typeof AppEditProfileRoute
  '/app/matches': typeof AppMatchesRoute
  '/app/profile': typeof AppProfileRoute
  '/chat/$matchId': typeof ChatMatchIdRoute
  '/invite/mentor': typeof InviteMentorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/choose-type'
    | '/diagnostics'
    | '/onboarding'
    | '/privacy'
    | '/verify-church'
    | '/verify-id'
    | '/app/admin-review'
    | '/app/discover'
    | '/app/edit-profile'
    | '/app/matches'
    | '/app/profile'
    | '/chat/$matchId'
    | '/invite/mentor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/choose-type'
    | '/diagnostics'
    | '/onboarding'
    | '/privacy'
    | '/verify-church'
    | '/verify-id'
    | '/app/admin-review'
    | '/app/discover'
    | '/app/edit-profile'
    | '/app/matches'
    | '/app/profile'
    | '/chat/$matchId'
    | '/invite/mentor'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/choose-type'
    | '/diagnostics'
    | '/onboarding'
    | '/privacy'
    | '/verify-church'
    | '/verify-id'
    | '/app/admin-review'
    | '/app/discover'
    | '/app/edit-profile'
    | '/app/matches'
    | '/app/profile'
    | '/chat/$matchId'
    | '/invite/mentor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChooseTypeRoute: typeof ChooseTypeRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  VerifyChurchRoute: typeof VerifyChurchRoute
  VerifyIdRoute: typeof VerifyIdRoute
  ChatMatchIdRoute: typeof ChatMatchIdRoute
  InviteMentorRoute: typeof InviteMentorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-id': {
      id: '/verify-id'
      path: '/verify-id'
      fullPath: '/verify-id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-church': {
      id: '/verify-church'
      path: '/verify-church'
      fullPath: '/verify-church'
      preLoaderRoute: typeof VerifyChurchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-type': {
      id: '/choose-type'
      path: '/choose-type'
      fullPath: '/choose-type'
      preLoaderRoute: typeof ChooseTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/mentor': {
      id: '/invite/mentor'
      path: '/invite/mentor'
      fullPath: '/invite/mentor'
      preLoaderRoute: typeof InviteMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$matchId': {
      id: '/chat/$matchId'
      path: '/chat/$matchId'
      fullPath: '/chat/$matchId'
      preLoaderRoute: typeof ChatMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matches': {
      id: '/app/matches'
      path: '/matches'
      fullPath: '/app/matches'
      preLoaderRoute: typeof AppMatchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/edit-profile': {
      id: '/app/edit-profile'
      path: '/edit-profile'
      fullPath: '/app/edit-profile'
      preLoaderRoute: typeof AppEditProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin-review': {
      id: '/app/admin-review'
      path: '/admin-review'
      fullPath: '/app/admin-review'
      preLoaderRoute: typeof AppAdminReviewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminReviewRoute: typeof AppAdminReviewRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppEditProfileRoute: typeof AppEditProfileRoute
  AppMatchesRoute: typeof AppMatchesRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminReviewRoute: AppAdminReviewRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppEditProfileRoute: AppEditProfileRoute,
  AppMatchesRoute: AppMatchesRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ChooseTypeRoute: ChooseTypeRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  VerifyChurchRoute: VerifyChurchRoute,
  VerifyIdRoute: VerifyIdRoute,
  ChatMatchIdRoute: ChatMatchIdRoute,
  InviteMentorRoute: InviteMentorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
